from __future__ import annotations

from typing import Protocol


class AdminCachePort(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, *, ttl_seconds: int) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def bump_version(self, namespace: str) -> int: ...

    async def get_version(self, namespace: str) -> int: ...
